### ISSUE TITLE
testsuite `errors` property is required

### ISSUE THREAD

**Issue by zerkms** [jstemmer/go-junit-report#101]
As per the https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd#L119 it's required to have `errors` attribute as well, otherwise the generated xml does not pass the xunit validation.

**Comment by patrickjane** [comment]
Hi, is there any ETA for a release for this? I'm trying to use `go-junit-report` in a jenkins pipeline, but it won't work because of the missing attributes, so I'm waiting for this patch.
