### ISSUE TITLE
Add properties to formatter.JUnitTestCase

### ISSUE THREAD

**Issue by tbpg** [jstemmer/go-junit-report#107]
Test cases can have properties. Would it be possible to add a `Properties` field to `formatter.JUnitTestCase`?

I'm doing some post processing of the output XML and would like to be able to unmarshal, add properties to test cases, and marshal again.

I'd be happy to send a PR if you're open to it.

**Comment by jstemmer** [comment]
None of the Junit schema definitions I've come across so far have properties for `testcase`, they only seem to appear in `testsuite`. So far I haven't had the need for testcase properties in go-junit-report and I'd prefer to avoid making custom changes to the JUnit schema without good reason. Do you have any examples of software that supports testcase properties?

**Comment by tbpg** [comment]
Thanks for taking a look. I no longer need the project I was working on that motivated this FR, so we can close this. :smiley:
