### ISSUE TITLE
module missing in go.mod with -mod=readonly

### ISSUE THREAD

**Issue by jerome-laforge** [jstemmer/go-junit-report#110]
I like to know if you can display correctly when module is missing in go.mod (that can be managed with gitlab for example)

```
go test -v -mod=readonly ./...
go: updates to go.mod needed, disabled by -mod=readonly
```

**Comment by jstemmer** [comment]
Can you provide a minimal example that reproduces this output when running `go test -v -mod=readonly`?

**Comment by jstemmer** [comment]
v2.0.0 might be able to handle this, but can't verify this without more information. Feel free to reopen this issue if it's still a problem.
