### ISSUE TITLE
Is it possible to generate both xml and json?

### ISSUE THREAD

**Issue by andresmonc** [jstemmer/go-junit-report#121]
Unfortunately Jenkins wants XML and Sonar wants JSON. Any way to work around this?

**Comment by KacperPerschke** [comment]
Does the pseudo JSON from the command
```sh
go test -json
```
meet the expectations of the Sonar application?

**Comment by jstemmer** [comment]
What kind of JSON is Sonar expecting? Can you give an example or link to a page describing the format Sonar needs?

**Comment by KacperPerschke** [comment]
@jstemmer  probably sonarqube ["Generic Issue Import Format"](https://docs.sonarqube.org/latest/analysis/generic-issue/) is the answear to your qestion.

If so I'ld ask @andresmonc **if** use of `go test` results as sonarqube input is a good idea. As I understand that `go test` is primarily intended for unit testing, and sonar for static code analysis. Which IMHO is another kind of a beast.

**Comment by jstemmer** [comment]
If the JSON Sonar expects is indeed for static code analysis, then `go-junit-report` is probably not the tool you need. In any case, without more information there's not much more we can do right now.
