### ISSUE TITLE
Deprecation of 'go get' for installing executables

### ISSUE THREAD

**Issue by mehrankamal** [jstemmer/go-junit-report#124]
In main readme file in Section: [Installation](https://github.com/jstemmer/go-junit-report#installation) we are using `go get` for installation which is deprecated as of `Go 1.17`. Details [here](https://golang.org/doc/go-get-install-deprecation)

We can update the instructions for using `go install` instead using the version suffix for installation as a binary.

I would be happy to open a pull request for resolving the issue and add instructions for `Go 1.17` in installation section.

**Comment by eccles** [comment]
Better still just make the executable available from a linhk so one does not to pollute on'e env with the deps for this package.
All ! want is the executable.

USe something like go releaser - https://github.com/goreleaser/goreleaser

**Comment by jstemmer** [comment]
Thanks for the heads up, I wasn't aware this was about to change for Go 1.18. I already wanted to make some other changes to the README, so I've updated this as well.
