### ISSUE TITLE
Parser gojson incompatibility with go test's -coverprofile flag

### ISSUE THREAD

**Issue by forsaken628** [jstemmer/go-junit-report#134]
When handle
[yy.txt](https://github.com/jstemmer/go-junit-report/files/8883375/yy.txt)

Generated report contain incorrect content like this
```xml
<testcase name="TestSrv_ServiceMap" classname="example.com/foo/pkg/labels" time="0.000">
	<error message="No test result found"></error>
</testcase>
```

command:
go test -json -race -coverpkg=./... -covermode=atomic -coverprofile=out/cover.out.tmp ./...

go version:
go 1.18

**Comment by jstemmer** [comment]
Thanks. It looks like the testcase gets attributed to the wrong package, possibly because of the order in which it appears in the output.

I don't think I've seen this before, it would be helpful if I could reproduce this output somehow. Can you share a bit more about the environment and the tests that you ran, e.g. what version of Go did you use and did you run any tests in parallel? Did you use any additional commandline options when running `go test`?

**Comment by jstemmer** [comment]
I managed to reproduce by testing multiple packages at a time and enabling the race detector (`-race`). For non-JSON output, test events are always grouped by package. When enabling JSON output this appears to not always be the case, test events from different packages may be mixed occasionally which triggers the bug you observed. Fortunately, each event in the JSON output contains the package name so this is fixable but it will require some refactoring.

Until this has been fixed you can work around this problem by disabling the race detector, or not use the JSON test output.

**Comment by karelbilek** [comment]
I have been hit by the same bug now. Yes this is fixable by looking at the JSON tag.

I can have a look at this and make a PR

**Comment by karelbilek** [comment]
I can give you another example that will cause this issue, even when there is no -race.

**Comment by karelbilek** [comment]
Ah, seems like we were using stable 2.0.0 version, which doesn't have this fixed, that's the reason. Nevermind!

**Comment by altego371** [comment]
**FYI**
If you are using a version without this fix you can use the next trick:
`go test -json [...] | jq -c '{k: .Package, v: .}' | sort | jq -c '.v' | go-junit-report [...]` where `[...]` are yours flags
 It sorts `go test` output before passing it to the `go-junit-report`.
 `jq` https://stedolan.github.io/ is a cli-tool for json.
