### ISSUE TITLE
build failures are ignored

### ISSUE THREAD

**Issue by ixdy** [jstemmer/go-junit-report#20]
One of our tests is currently failing to build.

Output from go 1.4.2 looks like the following:
```console
# k8s.io/kubernetes/pkg/registry/thirdpartyresourcedata/etcd
_output/local/go/src/k8s.io/kubernetes/pkg/registry/thirdpartyresourcedata/etcd/etcd_test.go:74: not enough arguments in call to test.TestCreate
_output/local/go/src/k8s.io/kubernetes/pkg/registry/thirdpartyresourcedata/etcd/etcd_test.go:100: not enough arguments in call to test.TestUpdate
FAIL    k8s.io/kubernetes/pkg/registry/thirdpartyresourcedata/etcd [build failed]
```

Passing this through go-junit-report, however, it's completely ignoring the build failure:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites></testsuites>
```

**Comment by jstemmer** [comment]
I didn't consider this before and I'm not sure if this should be handled by go-junit-report. It's not an individual testcase that fails, and I don't think the junit format supports reporting of build failures.

Is it enough to just detect a build failure? In that case you could try to capture the exit code of `go test` with the `$PIPESTATUS` variable. Another option would be to try and build the test binary first with `go test -c`. If that succeeds, run the test binary directly (support for this was added in PR #8).

If you think this should be included in the test report in some way, any suggestions on how to approach this would be helpful.

**Comment by ixdy** [comment]
Unfortunately `go test` doesn't seem to give an exit status that differentiates build failures from test failures; test failures seem to always exit with 1, but it seems that for build failures, it'll exit with either 1 or 2, depending on what stage failed.

Luckily, it seems that build failure messages are printed to stderr instead of stdout, so appropriately filtering stdout will be sufficient to allow the build failures to show.

Closing this issue as infeasible.
