### ISSUE TITLE
Json Output

### ISSUE THREAD

**Issue by zeushammer** [jstemmer/go-junit-report#22]
Would it be possible to have this support either xml or json?

**Comment by sectioneight** [comment]
JUnit is an XML format with a well defined schema. Many tools support junit as the de facto standard reporting format. What would it mean to support outputting as JSON? What tools would consume this? Why can't they ingest junit directly?

**Comment by daluu** [comment]
Others could also write a junit xml to json converter of the output as they desire I guess. Maybe such a converter already exists.

**Comment by jstemmer** [comment]
I'd rather not add JSON support to go-junit-report, JUnit is an XML format as @sectioneight already mentioned.

However, it should be fairly easy to write a tool that uses the `parser` package and outputs JSON.
