### ISSUE TITLE
Some issues pulling down the code with go

### ISSUE THREAD

**Issue by daluu** [jstemmer/go-junit-report#27]
Following the readme:

`go get -u github.com/jstemmer/go-junit-report`

returns a warning (or failure). On my local Mac, I get this:

`package github.com/jstemmer/go-junit-report: github.com/jstemmer/go-junit-report is a custom import path for https://github.com/jstemmer/go-junit-report, but /Users/daluu/go/src/github.com/jstemmer/go-junit-report is checked out from git@github.com:jstemmer/go-junit-report`

the code however does get pulled down to my Mac, but it doesn't automatically get built. So I had to manually build/install it afterwards with a `go install`.

and I was also testing use of it under CircleCI, which failed the CI build with this message:

`imports github.com/jstemmer/go-junit-report/parser: /home/ubuntu/.go_workspace/src/github.com/jstemmer/go-junit-report is from git@github.com:jstemmer/go-junit-report, should be from https://github.com/jstemmer/go-junit-report Action failed: go get -u github.com/jstemmer/go-junit-report`

also, don't know if it makes any difference, but I'm using SSH keys with Github for private repo authentication rather than providing username and password, but that probably shouldn't matter with this public repo I assume.

So in general, I have to do git clone, cd to the repo, then go install. For comparison, I did not encounter this issue with https://github.com/tebeka/go2xunit, although I prefer your solution over that one.

Anyone else ran into this before? Do you know what the underlying issue is? I've never hit this issue with other Github repos of go code.

**Comment by daluu** [comment]
It looks like removal of the "-u" parameter for upgrade will avoid the error message, and at the same time build the binary, at least when tested under CircleCI.

You might want to suggest in readme, for users to not use "-u" if installing & not upgrading go-junit-report.

**Comment by sectioneight** [comment]
You can always add `-f` to force the overwrite. This usually happens when you've checked it out under git+ssh but `go get` expects the `https` (read-only) github URL.

**Comment by daluu** [comment]
Thanks, good to know. But I wonder, why does it behave this way with the "-u" flag, and work fine w/o the "-u" flag?

The "-u" flag I believe is only needed if updating existing local copy of codebase? If first install, no need that flag.
