### ISSUE TITLE
The error message should be more meaningful

### ISSUE THREAD

**Issue by zhongyili** [jstemmer/go-junit-report#28]
I just run into an issue that if the 'go test -v' output is like the following:

=== RUN TestManifestOK
receivedManifestFile = true
manifestBytes : {
    "name" : "mysampleapp",
    "description" : "This is my hello world sample app",
    "version" : "1.0"
}--- PASS: TestManifestOK (0.00s)

Then the generated junit report will be like this:

```
    <testcase classname="builder" name="TestManifestOK" time="0.000">
        <failure message="Failed" type=""></failure>
    </testcase>
```

The 'Failed' reason I think is the '}' leading the '--PASS' which caused the parser cannot read it correctly, it is fine but hope the failure message could be more meaningful otherwise people get hard to know what is happening if he is not familiar with go-junit-report.

**Comment by Naatan** [comment]
Ran into the same bug, ie. if the `--- PASS:` line doesn't start from a new line it will be interpreted as failed.

**Comment by jstemmer** [comment]
This has already been fixed in a past version by ignoring any output before a test result.
