### ISSUE TITLE
Using go-junit-report with compiled go test

### ISSUE THREAD

**Issue by misabel** [jstemmer/go-junit-report#43]
I'm trying to use go-junit-report to convert the output of a go test binary file as such:
`./example.test | go-junit-report > results.xml` 
When I cat results.xml it returns an empty xml template like this:
`<testsuites><testsuites>`

How would I go about using go-junit-report without having to do `go test -v`

**Comment by robbert229** [comment]
For running your compiled test you will need to run `./example.test -test.v | go-junit-report > results.xml`

The important part is the `-test.v`, by default the test will only print PASS to stdout, thus giving you empty reports. I hope this helps. I ran into the same thing a couple of minutes a go!

**Comment by misabel** [comment]
Wow, worked like a charm. Thank you!
