### ISSUE TITLE
Tests with common name are represented incorrectly

### ISSUE THREAD

**Issue by ifn** [jstemmer/go-junit-report#47]
With [testify](https://github.com/stretchr/testify) we can create suites. Different suites may contain **tests with one name**. In such case go-junit-report defines second test in go test output as failed even if the second test passed.

Example:
**go test output**:
```
=== RUN   TestDiskWriteSuite
=== RUN   TestX
--- PASS: TestX (0.00s)
--- PASS: TestDiskWriteSuite (0.00s)
=== RUN   TestDiskWriteSuite2
=== RUN   TestX
--- PASS: TestX (0.00s)
--- PASS: TestDiskWriteSuite2 (0.01s)
PASS
ok  	command-line-arguments	0.018s
```
**go-junit-report output**:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="4" failures="1" time="0.018" name="command-line-arguments">
		<properties>
			<property name="go.version" value="go1.7"></property>
		</properties>
		<testcase classname="command-line-arguments" name="TestDiskWriteSuite" time="0.000"></testcase>
		<testcase classname="command-line-arguments" name="TestX" time="0.000"></testcase>
		<testcase classname="command-line-arguments" name="TestDiskWriteSuite2" time="0.010"></testcase>
		<testcase classname="command-line-arguments" name="TestX" time="0.000">
			<failure message="Failed" type=""></failure>
		</testcase>
	</testsuite>
</testsuites>
```

Tests may have common name if we don't use testify suites also.
Inside TestMain all package tests can be invoked multiple times via Run method (for example, with different global settings).
It will also produce repeated test names in go test log.

BTW [go2xunit](https://github.com/tebeka/go2xunit) handles that case correctly and shows two tests separately.

**Comment by jstemmer** [comment]
Unfortunately go-junit-report doesn't yet support any kind of non-standard test outputs, but it would be great if it did. Are you're willing to add support for testify? I'd be more than happy to discuss details and review code.

**Comment by sysradium** [comment]
Faced the same issue. Will think about the solution.

**Comment by jakubbujny** [comment]
hello @jstemmer - I'm thinking about implementing this feature just for fun so I have question to you: do you think that we can treat TestSuite just like Package struct used in your code ? As I can see packages are generating output in separate <testsuite> blocks (like in 06-report.xml in tests)

**Comment by jstemmer** [comment]
Do you mean that you want to create a separate package for every testsuite in the testify output? That could probably work. I haven't used testify myself however, so I'm not sure how easy it is to differentiate test suites from individual tests.

It's probably a good idea to first collect a few different testify outputs and think about how that would be represented in the resulting XML.

**Comment by jstemmer** [comment]
This appears to be fixed in v2, feel free to reopen if it's not the case.
