### ISSUE TITLE
"go.version" property uses version of Go used to compile the tool

### ISSUE THREAD

**Issue by nmiyake** [jstemmer/go-junit-report#48]
The `go.version` property in the output XML test report is the version of Go used to compile the `go-junit-report` tool (as opposed to the version of Go used to run the tests), which can be confusing.

(1) Compile `go-junit-report` using Go 1.7.5
(2) Change the local version of `go` to Go 1.8, run unit tests, and then use `go-junit-report` to transform the output.

Expected
----------
`go.version` should be `go1.8`

Actual
-------
`go.version` is `go1.7.5`

Cause
------
This is due to the call at https://github.com/jstemmer/go-junit-report/blob/master/junit-formatter.go#L82. This property is set and compiled into the `go-junit-report` binary itself, so once the binary is compiled the version is set.

There are 2 possible approaches I can think of for addressing this:

1. Make the program call `go version` and parse out the version string from there
  * This ensures that the version matches the version used by `go` at the time of invocation
  * However, this is not guaranteed to be correct since the original test output being processed may have been run using a different version of Go
2. Drop the `go.version` property altogether
  * Since it's impossible to determine the version of `go` that was used to generate the output being parsed, it might be better to omit this version entirely rather than to guess based on the runtime information or `go` executable information

Although this isn't critical, I think it would be nice to address. I'm running into this in my CI environment, where I build `go-junit-report` once, but then run my tests using different versions of `go` and process its output. All of the test output reports have a `go.version` property with a value of `go1.7.5` (the version of Go used to compile `go-junit-report`), but this is confusing to have for tests that were actually run using Go 1.8.

**Comment by jstemmer** [comment]
Yes, when I wrote that code (when only Go 1.0 existed) it was my intention for that property to contain the Go version used for the tests as opposed to the one used to compile the binary. I've been aware of this problem for quite some time but it never bothered me enough to do something about it. I agree that it's confusing and wouldn't mind seeing this fixed or removed. 

Another problem for option 1 (aside from calling the wrong binary and reporting the incorrect version) is what to do when the go binary is not even in the current PATH? I guess we could have an approach 3 where we make the caller responsible for providing the version to `go-junit-report`, perhaps through a flag?

Right now I'd probably prefer to just remove this field from the XML, but my concern is that we may break something for people who rely on the current behaviour or existence of this field.

**Comment by nmiyake** [comment]
Agree that all of those things sounds reasonable. I think for most `go` tools it's a fairly safe assumption that `go` is on the path (since tests are likely invoked by some form of `go test`), but it's true that this is not necessarily a safe assumption, especially if this tool is used for post-processing at a later time. Also, as noted, there's also not a guarantee that the version of `go` that exists on the path is the one that was used to run the tests, so this is still a best-effort that can be confusing when wrong.

Given this, I think the "correct" solutions are to either omit the field entirely, or keep the field but make the value user-provided (in which case it's the responsibility of the caller to ensure that the version that is provided is correct).

I think that the following could be a decently safe compromise that allows this customization while preserving back-compat:

* Allow the user to specify the version that is populated in the `go.version` property using a flag when invoking `go-junit-report`
  * If it's provided, the value will be used directly
  * Otherwise, current behavior is maintained

If you really care about phasing this out, you could mark as deprecated and then remove in the next major release, but this would allow the problem to be solved for now for people who care about it, while preserving the current behavior/output for those who don't.

**Comment by jstemmer** [comment]
Your approach with an optional flag sounds good to me. Do you mind sending me a PR with this change?

As for phasing it out, I'm not sure how I would mark it as deprecated and when to even remove it since I haven't really been making proper releases so far. Let's just preserve the current behaviour when the flag is not set.

**Comment by nmiyake** [comment]
Sure -- opened #49 as a PR to address this.

Agree that it's probably not worth the overhead of deprecating or phasing out in this case.
