### ISSUE TITLE
Packages that panic/fail before running any test are not reported

### ISSUE THREAD

**Issue by devnev** [jstemmer/go-junit-report#52]
If a package has tests but fails in an `init()`, the package in the report has no indication of this failure.

In case of a panic in an init(), the output will look like:
```
panic: the description of the panic here

goroutine 1 [running]:
panic(....)
   /usr/local/go/src/runtime/panic.go:500....
...more stack frames...
...more goroutines...
FAIL  package/name 0.01s
```

**Comment by rmmh** [comment]
Can you link to an example full output text, perhaps on https://gist.github.com?

**Comment by devnev** [comment]
https://gist.github.com/devnev/874da08d59c26d9e33a82fd13acd15d2

**Comment by jstemmer** [comment]
Thanks for the example, this was indeed not captured and reported. It looks like another failure on the package level (similar to a build failure), but there's nothing preceding it that would indicate what package it belongs to so we'll have to buffer the output until we encounter a package result. Would #53 work for your case?

**Comment by devnev** [comment]
LGTM.
