### ISSUE TITLE
False Failed reports for go test with -cpu flags

### ISSUE THREAD

**Issue by sergeyfd** [jstemmer/go-junit-report#54]
When we use `go test -v -cpu 1,2,4` command which makes tests to run three times with the different GOMAXPROCS settings go-junit-report generates lots of false `Failed` tests in the xml report.

**Comment by jstemmer** [comment]
Thanks for reporting this issue. It sounds like this is an example of tests appearing multiple times with the same name as originally mentioned in PR #53. The fix should be fairly simple.

**Comment by sergeyfd** [comment]
Thanks for fixing it. I checked it out and it works all right.
