### ISSUE TITLE
The generated results do not have the correct entry for testcases so Junit of jenkins will complain no test found. And the failed test result does not report the correct error msg

### ISSUE THREAD

**Issue by kaka0950** [jstemmer/go-junit-report#56]

**Comment by kaka0950** [comment]
When there is no test fail, there is no testcase node at all.

**Comment by jstemmer** [comment]
Can you give an example showing the test output and generated XML?

**Comment by kaka0950** [comment]
test output
ok  	something.com/services/name1	6.089s
ok  	something.com/name2	0.402s

generated XML is
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="0" failures="0" time="6.089" name="something.com/services/name1">
		<properties>
			<property name="go.version" value="go1.8"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.402" name="something.com/name2">
		<properties>
			<property name="go.version" value="go1.8"></property>
		</properties>
	</testsuite>
</testsuites>

**Comment by kaka0950** [comment]
[untitled text 2.txt](https://github.com/jstemmer/go-junit-report/files/1027824/untitled.text.2.txt)

**Comment by jstemmer** [comment]
I don't see any individual test output, how are you running the go test command? Did you specify the `-v` flag?

**Comment by kaka0950** [comment]
this 2 lines are the test output
ok something.com/services/name1	6.089s
ok something.com/name2	0.402s



no i do not use -v flag since it reports some failed tests which should not be reported

**Comment by kaka0950** [comment]
cat testouput.out | path/bin/go-junit-report -set-exit-code >> folder/report.xml

**Comment by jstemmer** [comment]
go-junit-report needs the additional information that is present when you run go test with the `-v` flag, otherwise the output doesn't contain the information needed to generate the individual testcases in the output report.
