### ISSUE TITLE
associate filename with test

### ISSUE THREAD

**Issue by thibaultfalque** [jstemmer/go-junit-report#57]
Hi, 
I use your tools for my [sonarqube plugin](https://github.com/uartois/sonar-golang). 

In sonarqube we must associate the tests with the test file. 

But actually all the tests is associate with the package. So is it possible adding the information about the filename that contain the test ? 

Thanks. 
Regards.

**Comment by jstemmer** [comment]
The `go test -v` output often doesn't contain the file name, in those cases it wouldn't be possible to associate the file with the test.

**Comment by thibaultfalque** [comment]
hi @jstemmer 
Thanks for your answer. 
I have created an issue for `go test`. 

Thanks.
