### ISSUE TITLE
Does go-junit-report actually require stderr from go test ?

### ISSUE THREAD

**Issue by wknapik** [jstemmer/go-junit-report#61]
The README says to use `go test -v 2>&1 | go-junit-report > report.xml`, with `2>&1` - is that really necessary ? It hides errors.

If it's not necessary, the `2>&1` should be removed from the README.

**Comment by jstemmer** [comment]
PR #45 added support for handling build errors. This is necessary to make sure both regular output and build errors on stderr are captured.

**Comment by wknapik** [comment]
But you're consuming the error message and leaving the user with no feedback.

If you re-printed the errors to stderr, or embedded the error information in the xunit report, that would be ok, but you don't, so `2>&1` is just not usable...

Personally, I'm using a makefile with
```
SHELL := $(shell which bash)
.SHELLFLAGS := -eo pipefail -c
```
and that takes care of detecting the build error, with no need for stderr parsing by go-junit-report.

Why not make it configurable with a switch ?

**Comment by Starefossen** [comment]
We just got bit by this outself...
