### ISSUE TITLE
Does it work for Ginkgo output?

### ISSUE THREAD

**Issue by hlltarakci** [jstemmer/go-junit-report#63]

**Comment by hlltarakci** [comment]
I think, this feature is especially helpful for projects that both use **testing** package and **ginkgo** tests together. 
I've noticed that, **go-junit-report** works as long as it finds following lines (_other lines are not important as i observe_):

```
=== RUN   TestInsertConfig
--- PASS: TestInsertConfig (0.00s)
```

However, Ginkgo produces some extra log before second line:

`SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 0 Skipped --- PASS: TestRest (0.03s)`

When i manually delete the preceding log, the tool works for **Ginkgo** as well. I believe, if you modify the code for this, it will naturally support Ginkgo output.

**Comment by Kernle32DLL** [comment]
This fails for the same reason as outlined in https://github.com/jstemmer/go-junit-report/issues/31

If [this PR ](https://github.com/jstemmer/go-junit-report/pull/64) gets merged, this tool will also work with Ginko

**Comment by jstemmer** [comment]
I've merged #64, can you give this another try and see if it works now?

**Comment by retr0h** [comment]
Does this still work with ginkgo v2?  I don't see my test suite displaying lines similar to the test case.  Could you confirm this still functions?  I'm executing the test suite as:

```
$ ginkgo -coverprofile cover.out ./... 2>&1 | go-junit-report
<?xml version="1.0" encoding="UTF-8"?>
<testsuites></testsuites>
```

**Comment by jstemmer** [comment]
I don't use ginkgo, so I don't know whether it works or not. From a quick look at their [docs](https://onsi.github.io/ginkgo/#generating-machine-readable-reports) it seems ginkgo can directly write JUnit reports, so you probably won't need go-junit-report.
