### ISSUE TITLE
Bench support

### ISSUE THREAD

**Issue by vkuzmin-uber** [jstemmer/go-junit-report#70]
Hello, me and my colleague @brittinator are using go-junit-report to convert test results to junit.xml and then jenkins uses it to shows us stats. 

junit.xml has a "time" field and go-junit-report fills it as well. But in go, we care about "time" mostly at Benchmark tests. We started to look for solution. As a first step, we think about results of "go test -bench=. -run= ..." in the junit.xml as well and use "time" field.

I think we can even do it without extra modes/flags but naturally like:

go test >test.log
go test -bench=. -run=BenchmarkIpsHistoryLookup -benchmem -count 20 project/* >> test.log
cat test.log | | go-junit-report > report.xml

Note that we want to make a smart converter that takes in account -count at least and I think we can avoid regression (or we can add flags if there is any risk)

The questions:
1) Have you considered adding Benchmarks to the tool? If so, please share details or give us a link to previous discussion.
2) We are willing to contribute and provide this functionality. Would you accept it to main branch?

**Comment by jstemmer** [comment]
I've never considered adding bencharking to `go-junit-report` and I don't think this has ever come up before. This definitely sounds interesting, but I'd like to know a bit more about how your proposed solution would work. What would a `report.xml` look like if it included benchmark information? Would a tool like Jenkins be able to handle this reasonably well?

**Comment by vkuzmin-uber** [comment]
Lets look at output of benchmark:

go test -bench=. -benchmem > bench.log

cat bench.log

goos: darwin
goarch: amd64
pkg: code.internal/state
BenchmarkIpsHistoryInsert-8   	   30000	     52568 ns/op	   24879 B/op	     494 allocs/op
BenchmarkIpsHistoryLookup-8   	  100000	     15208 ns/op	    7369 B/op	     143 allocs/op
PASS
ok  	code.uber.internal/infra/swn-observer/custodian/state	9.415s

Now, lets try go-junit-report with this output:

cat bench.log | go-junit-report

<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="0" failures="0" time="9.415" name="code.nternal/state">
		<properties>
			<property name="go.version" value="go1.9.2"></property>
		</properties>
	</testsuite>
</testsuites>

So, it has aggregated "time" of this run only that is useless because in case of benchmarks it depends on iterations that are random. 

I suggest:
1)  add "testcase" for every benchmark (as script does now for tests):

       <testsuite tests="4" failures="0" time="0.000067776" name="code.nternal/state/BenchmarkRingValue">
		<properties>
			<property name="go.version" value="go1.9.2"></property>
		</properties>
            <testcase classname="changes" name="BenchmarkIpsHistoryInsert" time="0.000052568"></testcase>
            <testcase classname="changes" name="BenchmarkIpsHistoryLookup" time="0.000015208"></testcase>
	</testsuite>

2) Calculate Total time as a sum of testcases's values
3) If benchmark started with flag -count N, there will be N lines like:

BenchmarkIpsHistoryInsert-8   	   30000	     52568 ns/op	   24879 B/op	     494 allocs/op
BenchmarkIpsHistoryInsert-8   	   10000	     48168 ns/op	   24879 B/op	     494 allocs/op
BenchmarkIpsHistoryInsert-8   	   15000	     49199 ns/op	   24879 B/op	     494 allocs/op

script should be able to take an average.

**Comment by jstemmer** [comment]
Sounds good to me, the implementation should be fairly simple.

I'd suggest using a new `Benchmark` type in the parser. Since the JUnit report XML spec is limited in what it can represent we should make the formatter responsible for merging benchmarks with the same name and calculating the average ns/op and total duration.

**Comment by brittinator** [comment]
Great thanks for getting back to us and the info on the `Benchmark` parser type. I should have implementation+tests available in around a month.
