### ISSUE TITLE
Please provide releases with binaries

### ISSUE THREAD

**Issue by ahammond** [jstemmer/go-junit-report#77]
using `go get` in my build pipeline is kinda evil. I'd like to lock dependencies to specific versions. I'd like to fetch the binary from release artifacts. For example, https://github.com/ahammond/ipcheck/releases provides this using CircleCI https://github.com/ahammond/ipcheck/blob/master/.circleci/config.yml#L26

**Comment by jstemmer** [comment]
Thanks, that's a good suggestion. I'll look into setting this up and providing release binaries when I get some time.

**Comment by kishaningithub** [comment]
For automated generation of go binaries and publishing in github
https://goreleaser.com/introduction/
For creating an automagical install script that uses binaries from github releases
https://github.com/goreleaser/godownloader

**Comment by kishaningithub** [comment]
For inspiration you can look into [golangci-lint ](https://github.com/golangci/golangci-lint) which uses both [goreleaser](https://goreleaser.com/introduction/) as well as [godownloader](https://github.com/goreleaser/godownloader)

@ahammond IMHO you should shift to this as well as you can generate brew taps, rpm and dep packages etc as well and all that has to be done is put in a yaml file and a CI integration

**Comment by ahammond** [comment]
@kishaningithub that's pretty slick.  I might just switch!

**Comment by Starefossen** [comment]
If anyone are interested we are providing pre built binaries go-junit-report for linux and macos here: https://github.com/bulderbank/go-junit-report/releases

**Comment by jstemmer** [comment]
Binaries can be downloaded from the Releases page: https://github.com/jstemmer/go-junit-report/releases
